// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsMW9E6uUNexWH-bx8rcZ9mF74LORQYkc',
    appId: '1:148560058818:web:291c26453b91e7dda31e5b',
    messagingSenderId: '148560058818',
    projectId: 'sync-5c67a',
    authDomain: 'sync-5c67a.firebaseapp.com',
    storageBucket: 'sync-5c67a.firebasestorage.app',
    measurementId: 'G-CXVLLHTPCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLxFRFP3enEMTWHjWsBPNtPifidrP5rs',
    appId: '1:148560058818:android:6c91f91ced36ed81a31e5b',
    messagingSenderId: '148560058818',
    projectId: 'sync-5c67a',
    storageBucket: 'sync-5c67a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSPoBUqpk2wttQG0rCqFsIun3T9dpYAa4',
    appId: '1:148560058818:ios:5c596333e0907342a31e5b',
    messagingSenderId: '148560058818',
    projectId: 'sync-5c67a',
    storageBucket: 'sync-5c67a.firebasestorage.app',
    iosBundleId: 'com.example.syncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSPoBUqpk2wttQG0rCqFsIun3T9dpYAa4',
    appId: '1:148560058818:ios:5c596333e0907342a31e5b',
    messagingSenderId: '148560058818',
    projectId: 'sync-5c67a',
    storageBucket: 'sync-5c67a.firebasestorage.app',
    iosBundleId: 'com.example.syncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsMW9E6uUNexWH-bx8rcZ9mF74LORQYkc',
    appId: '1:148560058818:web:fe169ae2326083cea31e5b',
    messagingSenderId: '148560058818',
    projectId: 'sync-5c67a',
    authDomain: 'sync-5c67a.firebaseapp.com',
    storageBucket: 'sync-5c67a.firebasestorage.app',
    measurementId: 'G-DK07TP37S4',
  );
}
